# Generated by Django 4.2.11 on 2024-05-23 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории товара')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('processing_date', models.DateField(blank=True, null=True, verbose_name='Срок принятия заказа')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photos_product/%Y/%m/%d/', verbose_name='Изображение')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.categoryproduct')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-date_created'],
            },
        ),
    ]
